name: CD Pipeline

on:
  workflow_run:
    workflows: ["nginx"]
    types:
      - completed
jobs:

  build:

    runs-on: ip-172-31-36-165

    steps:
    - name: Pull Docker image
      run: docker pull prabhusamarla/githubaction-nginx:latest
    - name: Delete Old docker container
      run: docker rm -f nginx || true
    - name: Run Docker Container
      run: docker run -d -p 80:80 --name nginx-container prabhusamarla/githubaction-nginx
