name: CD Nginx pipeline

on:
  workflow_run:
    workflows: ["Nginx Pipeline"]
    types:
      - completed
  push:
    branches:
      - nginx

jobs:
  build:
    runs-on: self-hosted # or specify the actual runner label you are using

    steps:
    - name: Pull Docker image
      run: docker pull prabhusamarla/githubaction-nginx:latest
    - name: Delete Old docker container
      run: docker rm -f nginx || true
    - name: Run Docker Container
      run: docker run -d -p 80:80 --name nginx-container prabhusamarla/githubaction-nginx
