name: Terraform Deploy

on:
  push:
    branches:
      - main
      - develop
      - terraform-ec2

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: us-east-1
        run: |
           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
           aws configure set region $AWS_DEFAULT_REGION

      - name: Terraform Init
        run: terraform init

      - name: Make Script Executable
        run: chmod +x ./determine_env.sh
    
      - name: Determine Environment Variables File
        id: env-vars
        run: ./determine_env.sh

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var-file=environments/${{ env.tfvars_file }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Upload Plan for Approval
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: tfplan

  # Terraform Apply Job (Separate from Plan)
  terraform-apply:
    needs: terraform
    runs-on: ubuntu-latest
    if: github.ref_name == 'terraform-ec2' # Ensure this only runs for the main branch

    steps:
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
